package com.example.autowebgenerator.model.entity;

import com.mybatisflex.annotation.Column;
import com.mybatisflex.annotation.Id;
import com.mybatisflex.annotation.KeyType;
import com.mybatisflex.annotation.Table;
import lombok.Data;

import java.io.Serial;
import java.io.Serializable;
import java.util.Date;

/**
 * User entity — mapped to the 'users' table (PostgreSQL).
 * Column names use snake_case; MyBatis Flex's default camelCase→snake_case
 * mapping resolves them automatically.
 */
@Data
@Table(value = "users")
public class User implements Serializable {

    @Serial
    private static final long serialVersionUID = 1L;

    /** Primary key — Snowflake ID generated by the application. */
    @Id(keyType = KeyType.Generator, value = "snowFlakeId")
    private Long id;

    /** Login account → column: user_account */
    private String userAccount;

    /** Encrypted password (MD5 + salt) → column: user_password */
    private String userPassword;

    /** Display name → column: user_name */
    private String userName;

    /** Avatar URL → column: user_avatar */
    private String userAvatar;

    /** Short bio → column: user_profile */
    private String userProfile;

    /** Role: "user" | "admin" → column: user_role */
    private String userRole;

    /** Last time the user edited their own profile → column: edit_time */
    private Date editTime;

    /** Record creation time → column: create_time */
    private Date createTime;

    /** Record last-update time (auto-updated by trigger) → column: update_time */
    private Date updateTime;

    /** Logical delete flag: 0 = active, 1 = deleted → column: is_delete */
    @Column(isLogicDelete = true)
    private Integer isDelete;
}
